update ip and adding a test

diff --git a/jenkins_docker b/jenkins_docker
--- a/jenkins_docker
+++ b/jenkins_docker
@@ -2,8 +2,8 @@ pipeline {
     agent any
 
     environment {
-        EC2_test_IP = "35.159.23.172"
-        EC2_prod_IP = "3.120.172.175"
+        EC2_test_IP = "18.185.15.37"
+        EC2_prod_IP = "18.195.117.231"
     }
 
     stages {
@@ -56,8 +56,39 @@ pipeline {
                 }
             }
         }  
-              
-        stage('Running Docker') {
+
+         stage('Test Docker') {
+            steps {
+                withCredentials([sshUserPrivateKey(credentialsId: 'ssh-testing', keyFileVariable: 'SSH_PRIVATE_KEY')]) {
+                    sshagent(['ssh-testing']) {
+                        sh """
+                        ssh -o StrictHostKeyChecking=no -i $SSH_PRIVATE_KEY ec2-user@${EC2_prod_IP} '
+                            pwd
+                            docker-compose down
+                            docker image prune -a
+                            docker container prune -f
+                            docker rmi -f liorfizz/alpaca
+                            rm -rf ~/ci-cd/ || true
+                            docker pull liorfizz/alpaca
+                            git clone https://github.com/liorfizz/ci-cd.git
+                            cd ci-cd/alpacaflask/ && cp docker-compose.yml ~
+                            docker-compose up -d
+                            echo "Testing...."
+                            curl_output=$(curl -s -o /dev/null -w "%{http_code}" http://${EC2_test_IP}:5000)
+                            if [ $curl_output -eq "200" ]; then
+                                echo "Site is working (200 OK)"
+                            else
+                                echo "Error: Site is not working"
+                                exit 1
+                            fi  
+                        '
+                        """
+                    }
+                }
+            }
+        }
+
+        stage('Deploy Docker') {
             steps {
                 withCredentials([sshUserPrivateKey(credentialsId: 'ssh-testing', keyFileVariable: 'SSH_PRIVATE_KEY')]) {
                     sshagent(['ssh-testing']) {
