bug fix in pipeline testing

diff --git a/jenkins_docker b/jenkins_docker
--- a/jenkins_docker
+++ b/jenkins_docker
@@ -72,16 +72,17 @@ pipeline {
                             docker pull liorfizz/alpaca
                             git clone https://github.com/liorfizz/ci-cd.git
                             cd ci-cd/alpacaflask/ && cp docker-compose.yml ~
-                            docker-compose up -d
-                            echo "Testing...."
-                            curl_output=$(curl -s -o /dev/null -w "%{http_code}" http://${EC2_test_IP}:5000)
-                            if [ $curl_output -eq "200" ]; then
-                                echo "Site is working (200 OK)"
-                            else
-                                echo "Error: Site is not working"
-                                exit 1
-                            fi  
+                            docker-compose up -d 
                         '
+                        
+                        echo "Testing...."
+                        curl_output=$(curl -s -o /dev/null -w "%{http_code}" http://${EC2_test_IP}:5000)
+                        if [ $curl_output -eq "200" ]; then
+                        echo "Site is working (200 OK)"
+                        else
+                        echo "Error: Site is not working"
+                        exit 1
+                        fi 
                         """
                     }
                 }
