add testing stage

diff --git a/jenkins_docker b/jenkins_docker
--- a/jenkins_docker
+++ b/jenkins_docker
@@ -67,7 +67,7 @@ pipeline {
             }
         }  
 
-        stage('Test Docker') {
+        stage('Deploy Test') {
             steps {
                 withCredentials([sshUserPrivateKey(credentialsId: 'ssh-testing', keyFileVariable: 'SSH_PRIVATE_KEY')]) {
                     sshagent(['ssh-testing']) {
@@ -83,22 +83,32 @@ pipeline {
                             git clone https://github.com/liorfizz/ci-cd.git
                             cd ci-cd/alpacaflask/ && cp docker-compose.yml ~
                             docker-compose up -d 
-                        '
-                        echo "testing...."
-                        curl_output=$(curl -s -o /dev/null -w "%{http_code}" http://${EC2_test_IP}:5000)
-                        if [ $curl_output -eq "200" ]; then
-                            echo "Site is working (200 OK)"
-                        else
-                            echo "Error: Site is not working"
-                            exit 1
-                        fi   
+                        ' 
                         """
                     }
                 }
             }
         }
 
-        stage('Deploy Docker') {
+        stage('Testing Q/A') {
+            steps {
+                withCredentials([sshUserPrivateKey(credentialsId: 'ssh-testing', keyFileVariable: 'SSH_PRIVATE_KEY')]) {
+                    sshagent(['ssh-testing']) {
+                        sh """
+                        curl_output=$(curl -s -o /dev/null -w "%{http_code}" http://${EC2_test_IP}:5000)
+                        if [ $curl_output -eq "200" ]; then
+                            echo "Site is working (200 OK)"
+                        else
+                            echo "Error: Site is not working"
+                            exit 1
+                        fi 
+                        """
+                    }
+                }
+            }
+        }
+
+        stage('Deploy Production') {
             steps {
                 withCredentials([sshUserPrivateKey(credentialsId: 'ssh-testing', keyFileVariable: 'SSH_PRIVATE_KEY')]) {
                     sshagent(['ssh-testing']) {
